### ISSUE TITLE
 How to use multiple GPUs to train and test the network?

### ISSUE THREAD

**Issue by lhc11171552** [heshuting555/TransReID#11]
I used two GPUs to train the network, and was an error： ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set

**Comment by michuanhaohao** [comment]
`CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 66666 train.py --config_file configs/VehicleID/vit_transreid_stride.yml MODEL.DIST_TRAIN True`

Sometimes you may encounter some errors because of the cuda driver. Please run the shell again after killing CUDA pids (if necessary).

**Comment by michuanhaohao** [comment]
Two gpus:

CUDA_VISIBLE_DEVICES=0,1
--nproc_per_node=2
Batch size * 2

**Comment by lhc11171552** [comment]
Thanks,I will have a try
